# .github/workflows/deploy.yml
name: Deploy ML API

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests (optional)
      run: |
        echo "No tests yet, but you could add pytest here"

    - name: Build Docker image
      run: docker build -t ml-api .

    - name: Push to Docker Hub (optional)
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      run: |
        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
        docker tag ml-api $DOCKER_USER/ml-api:latest
        docker push $DOCKER_USER/ml-api:latest
